import {client} from './client';

export const CLIENTS: client[] = [
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
  {
    name: 'Webkit',
    phone: 512345678,
    email: 'test@test.com',
    area: 'test',
    group: 'test',
    company: 'test',
  },
];
